### PR TITLE
Add versionIRI metadata to nmrCV.owl release file

### LINKED ISSUE #189: add "versionIRI" annotation to nmrCV.owl
It is best to not only provide an owl:versionInfo annotation but also one for the IRI of the specific version using owl:versionIRI.

### PR DESCRIPTION
**Pull request by StroemPhi**
This PR edits the `nmrCV.owl` release file living under `https://github.com/nmrML/nmrML/blob/gh-pages/cv/v1.1.0/nmrCV.owl`, which, I assume, was copied into the webspace of the nmrML.org website to this path `http://nmrml.org/cv/v1.1.0/nmrCV.owl`, from where nmrCV is served.
It adds an `owl: versionIRI` metadata assertion that points to `http://nmrml.org/cv/v1.1.0/nmrCV.owl` as the version IRI. This ensures that at least the version IRI within the nmrCV.owl is resolvable, once this PR is accepted and this file is overwritten on the nmrml.org server. 
So this PR is a small step in the direction of addressing https://github.com/nmrML/nmrCV/issues/23.
It also fixes #189 partially.  Partially, because this addition should also be done on the source itself (https://github.com/nmrML/nmrML/blob/master/ontologies/nmrCV.owl) to ensure that this edit persists, once the automatic doc build pipeline (about which I know nothing) would be rerun, and its GH-pages output would be copied back onto the nmrml.org server.

### CODE REVIEW

**Comment by StroemPhi** [comment]
Testing with curl:
```
C:\Users\stroemertp>curl -I http://nmrml.org/cv/v1.1.0/nmrCV.owl
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 457554
Server: GitHub.com
Content-Type: application/rdf+xml
Last-Modified: Wed, 07 Aug 2024 18:45:50 GMT
Access-Control-Allow-Origin: *
ETag: "66b3c0de-6fb52"
expires: Thu, 08 Aug 2024 14:14:45 GMT
Cache-Control: max-age=600
x-proxy-cache: MISS
X-GitHub-Request-Id: B394:341630:2B625E:2C2B7C:66B4D07D
Accept-Ranges: bytes
Age: 0
Date: Thu, 08 Aug 2024 17:48:11 GMT
Via: 1.1 varnish
X-Served-By: cache-fra-eddf8230057-FRA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1723139291.234915,VS0,VE107
Vary: Accept-Encoding
X-Fastly-Request-ID: 68d31c32a51c3b751f0062d6077ca7be944f5a37
```

**Comment by StroemPhi** [comment]
As @sneumann writes [here](https://github.com/nmrML/nmrCV/issues/23#issuecomment-2273790057), there exists no webserver other than the GH pages, so the DNS configuration of nmrML.org points directly there.

**Comment by sneumann** [comment]
To me, it looks like the PR can be merged now. Correct ? Yours, Steffen

**Comment by StroemPhi** [comment]
Yes can be merged @sneumann. Only my assumption of the extra web space was wrong. So this fix will improve the metadata of the file that lives in the GH pages. We should make the same changes for the equivalent version that lives in the repo's main branch, to synch both in a separate PR, as the former was autogenerated from the latter.

**Comment by sneumann** [comment]
Hi, I made required changes on the GH-pages branch. Thanks, Steffen

**Pull request merged**
